# Generated by Django 5.0.2 on 2024-03-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_adminuser_admin'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminUser',
        ),
    ]
