# Generated by Django 5.0.2 on 2024-03-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_admin_adminuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='CustomUser',
        ),
    ]
