# Generated by Django 5.0.2 on 2024-03-03 02:34

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_adminuser_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fathername',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idNationalNumber',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idNumber',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mothername',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roomNumber',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='typejob',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unitNumber',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
